# Generated by Django 4.2.11 on 2024-03-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
