# Generated by Django 4.2.11 on 2024-03-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0002_expense_monthly_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='login_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
