# Generated by Django 4.2.11 on 2024-03-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0003_expense_login_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='login_password',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
