# Generated by Django 4.2.11 on 2024-03-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0004_expense_login_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
