# Generated by Django 4.2.11 on 2024-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='g_email',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
