# Generated by Django 4.2.11 on 2024-03-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0006_user_g_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdb',
        ),
    ]
