# Generated by Django 4.2.11 on 2024-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0007_rename_user_userdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
