# Generated by Django 4.2.11 on 2024-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0008_userdb_monthly_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
