# Generated by Django 4.2.11 on 2024-03-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0010_remove_expense_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
